spring:
  application:
    name: user-info-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  zipkin:
    base-url: http://localhost:9400
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
        
server:
   port: 8801

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8700/eureka 

db:
 name: mysql
 schema: userinfo
 username: produser
 password: prodpass
 
